### ISSUE TITLE
Admin Routing issues

### ISSUE THREAD

**Issue by nehal83** [elgentos/magento2-prismicio#10]
I can't add a new route via the admin, seems to keep routing to the same URL.

Logs are showing the following `main.DEBUG: Request validation failed for action "Magento\Framework\App\Action\Forward\Interceptor"`

Any advice? Thanks.

**Comment by JeroenBoersma** [comment]
Hi @nehal83 because of the pre-beta this isn't implemented yes.... 

Related issue https://github.com/elgentos/magento2-prismicio/issues/1

So, this is a open invitation to create the edit/add forms :-)

Otherwise this will show up in the upcoming weeks

**Comment by JeroenBoersma** [comment]
To help you out a bit, what already works:

Tables: `prismicio_route` and `prismicio_routes_store`

If you have a single store configuration:

First setup Prismic:

In Prismic: Settings -> API -> Add Permanent Access token

In Magento: System -> Configuration -> Services -> PrismicIO
- Enable
- API endpoint: Copy/paste from Prismic
- API secret: Client Secret

For now, db it is!

Add a record to table `prismicio_route`

- `title`: Pick your poison: `Blog posts`
- `content_type`: PrismicIO Custom type ?: `post`
- `route`: Main route on your store ?: `/blog`
- `status`: Enabled ?: `1`

Add a record to table `prismicio_route_store`
- `route_id`: Just created route ?: `1`
- `store_id`: Store id ?: `1`

Make sure your custom type in Prismic has a uid field which will be the slug.

Navigate to `/blog/YOURUID` should open the page in Magento.
Because of the nature of configurations, after that you can start setting up your content types.

I've added some examples in https://github.com/elgentos/magento2-prismicio-sample-data
If development mode is enabled it'll show debug info, this is only if developmentmode is enabled

**Comment by nehal83** [comment]
Hi Jeroen,

This was a lot of help, thanks a lot. I've got it working by adding records to the DB itself.

Nehal

**Comment by TimPietrusky** [comment]
@JeroenBoersma What is the status on this?

**Comment by JeroenBoersma** [comment]
Yes, I didn't look at it again, will see if I can pick this up shortly, need to update the backend files :)

Was maybe hoping someone else with a lot of UI backend experience would pick this up, hehe...

**Comment by JeroenBoersma** [comment]
But it wasn't really lost, it was still waiting here of coarse :)

**Comment by peterjaap** [comment]
@JeroenBoersma we're now exactly a year later! :tada:

**Comment by peterjaap** [comment]
See https://github.com/elgentos/magento2-prismicio/pull/48

**Comment by peterjaap** [comment]
Merged & released https://github.com/elgentos/magento2-prismicio/releases/tag/1.6.3
