### ISSUE TITLE
Sharing the page on Moblie device copies Prismic directly url instead of homepage

### ISSUE THREAD

**Issue by henkvalk** [elgentos/magento2-prismicio#57]
When you want to share the homepage URL on your mobile device, the directly Prismic URL will be shared instead of the homepage normal URL

![File](https://user-images.githubusercontent.com/8955854/138264771-f54954ae-0096-49a8-93f4-af3aa9d09c5e.jpg) 

![url_sharing](https://user-images.githubusercontent.com/8955854/138264603-f9c81d47-bfaa-4319-93c0-d91b096bd7c3.png)

**Comment by henkvalk** [comment]
apologies for the full page images....

**Comment by jesse-deboer** [comment]
This is due to a wrong configuration with the canonical url. The canonical url should not show the Prismic link, the Prismic link should only show a canonical url to the right url.

So:
- https://www.dekistenkoning.nl should **not** have a canonical
- https://www.dekistenkoning.nl/prismicio/direct should have a canonical to https://www.dekistenkoning.nl

Also see the Facebook debugger:
![image](https://user-images.githubusercontent.com/14839421/138312979-46103957-b407-4a02-aeab-09105a7620ab.png)

This is something that needs to be fixed in the module

**Comment by peterjaap** [comment]
It has been fixed in a few of our installs though, maybe @ArjenMiedema has some tips?

**Comment by henkvalk** [comment]
Any thoughts ?

**Comment by JeroenBoersma** [comment]
Yes, we have a seperate block on the homepages! Sorry for the late reply :)

Can easily be fixed with a layout/template file in your theme!

`app/design/frontend/Vendor/theme/Elgentos_PrismicIO/prismicio_by_uid_kistenkoning.xml` *uid* comes from Prismic
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<page layout="no-columns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <block class="Magento\Framework\View\Element\Template" name="alternate.links.head.home" template="Elgentos_PrismicIO::alternate_links_home.phtml" />
        <move element="alternate.links.head.home" destination="head.additional" />

        <referenceBlock name="prismicio_alternate_links" remove="true" />
        <referenceBlock name="prismicio_canonical" remove="true" />

    </body>
</page>
```

`app/design/frontend/Vendor/theme/Elgentos_PrismicIO/templates/alternate_links_home.phtml`
```php
  <link rel="alternate" hreflang="nl-NL" href="https://www.dekistenkoning.nl/" type="text/html" />
  <link rel="alternate" hreflang="x-default" href="https://www.dekistenkoning.nl/" type="text/html" />
  <link rel="alternate" hreflang="en-US" href="https://www.kingofcrates.co.uk/" type="text/html" />
  <link rel="canonical" href="<?= $block->getUrl('') ?>" />
```

**Comment by peterjaap** [comment]
I found an even easier solution, if you don't need the `alternate` URLs. I have a custom type Homepage which contains my homepage(s). In that case, just create the file `app/design/frontend/Vendor/Theme/Elgentos_PrismicIO/templates/canonical.phtml` and use this;

```
<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<link rel="canonical" href="<?= $block->getRequest()->getParam('type') === 'homepage' ? $block->getUrl('') : $block->getCanonicalUrl() ?>" />
```
